import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { aiSummary, generateActionPlan, type PriorityReport } from "./mock-data";

export function exportPriorityPdf(
  reports: PriorityReport[],
  opts?: { issueFilter?: string; severityFilter?: string },
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const now = new Date();

  // Header
  doc.setFillColor(29, 60, 120);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Pacific Response Intelligence", margin, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Priority Response Report", margin, 50);
  doc.text(now.toLocaleString(), pageWidth - margin, 50, { align: "right" });

  let y = 100;
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Priority Response List", margin, y);
  y += 6;

  if (opts?.issueFilter && opts.issueFilter !== "all") {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    y += 12;
    doc.text(`Issue filter: ${opts.issueFilter}`, margin, y);
  }
  if (opts?.severityFilter && opts.severityFilter !== "all") {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    y += 12;
    doc.text(`Severity filter: ${opts.severityFilter}`, margin, y);
  }

  autoTable(doc, {
    startY: y + 10,
    margin: { left: margin, right: margin },
    head: [["Area", "Issue", "Severity", "People", "Status", "AI Score", "Action"]],
    body: reports.map((r) => [
      r.area,
      r.issue,
      r.severity,
      r.peopleAffected.toLocaleString(),
      r.status ?? "New",
      String(r.riskScore),
      r.action,
    ]),
    styles: { fontSize: 9, cellPadding: 6, textColor: [30, 30, 30] },
    headStyles: { fillColor: [29, 60, 120], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 248, 252] },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 2) {
        const sev = String(data.cell.raw);
        const color: [number, number, number] =
          sev === "Critical" ? [200, 40, 50] :
          sev === "High" ? [220, 110, 30] :
          sev === "Medium" ? [200, 150, 30] :
          [40, 140, 90];
        data.cell.styles.textColor = color;
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let cy = (doc as any).lastAutoTable.finalY + 26;
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxWidth = pageWidth - margin * 2;

  const ensureSpace = (needed: number) => {
    if (cy + needed > pageHeight - 50) {
      doc.addPage();
      cy = 60;
    }
  };

  // Changes since last update
  const changed = reports.filter(
    (r) =>
      (r.previousRiskScore != null && r.previousRiskScore !== r.riskScore) ||
      (r.previousSeverity != null && r.previousSeverity !== r.severity),
  );
  if (changed.length) {
    ensureSpace(60);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text("Changes since last update", margin, cy);
    cy += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    for (const r of changed) {
      const delta = r.previousRiskScore != null ? r.riskScore - r.previousRiskScore : 0;
      const arrow = delta > 0 ? "▲" : delta < 0 ? "▼" : "•";
      const sevChange =
        r.previousSeverity && r.previousSeverity !== r.severity
          ? ` (severity ${r.previousSeverity} → ${r.severity})`
          : "";
      const line = `${arrow} ${r.area}: risk ${r.previousRiskScore ?? "—"} → ${r.riskScore}${delta ? ` (${delta > 0 ? "+" : ""}${delta})` : ""}${sevChange}`;
      const lines = doc.splitTextToSize(line, maxWidth) as string[];
      for (const l of lines) {
        ensureSpace(14);
        doc.text(l, margin, cy);
        cy += 14;
      }
    }
    cy += 8;
  }

  // AI Response Action Plan (top 3)
  const top3 = [...reports].sort((a, b) => b.riskScore - a.riskScore).slice(0, 3);
  if (top3.length) {
    ensureSpace(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text("AI Response Action Plan", margin, cy);
    cy += 6;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    cy += 12;
    doc.text("Generated by Gemini AI Agent — top 3 priority areas.", margin, cy);
    cy += 14;

    for (const r of top3) {
      ensureSpace(30);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(29, 60, 120);
      doc.text(`${r.area} — ${r.issue} · risk ${r.riskScore}`, margin, cy);
      cy += 14;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const plan = generateActionPlan(r);
      plan.forEach((p, i) => {
        const lines = doc.splitTextToSize(`${i + 1}. ${p.step}  [${p.eta}]`, maxWidth) as string[];
        for (const l of lines) {
          ensureSpace(14);
          doc.text(l, margin, cy);
          cy += 14;
        }
      });
      cy += 6;
    }
  }

  // Gemini summary
  ensureSpace(40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Gemini AI Response Summary", margin, cy);
  cy += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  const paragraphs = aiSummary.split("\n\n");
  for (const para of paragraphs) {
    const lines = doc.splitTextToSize(para, maxWidth) as string[];
    for (const line of lines) {
      ensureSpace(14);
      doc.text(line, margin, cy);
      cy += 14;
    }
    cy += 6;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(
      "Built for smarter, safer, and more resilient Pacific communities.",
      margin,
      pageHeight - 20,
    );
    doc.text(`Page ${i} / ${pageCount}`, pageWidth - margin, pageHeight - 20, { align: "right" });
  }

  const stamp = now.toISOString().slice(0, 10);
  doc.save(`pacific-response-priority-${stamp}.pdf`);
}
